#MakeFile 

#target: dependency1 dependency2 ...
#	<tab> command

#NOTE: remember to add the TAB character before the command part

#Typing 'make' will invoke the first target entry in the file
seaice: seaice.cpp
	g++ -o seaice seaice.cpp



