#MakeFile 

#target: dependency1 dependency2 ...
#	<tab> command

#NOTE: remember to add the TAB character before the command part

#Typing 'make' will invoke the first target entry in the file
encode: insertion_encoding.cpp
	g++ -o encode insertion_encoding.cpp
decode: decode.cpp
	g++ -o decode decode.cpp


