#MakeFile 

#target: dependency1 dependency2 ...
#	<tab> command

#NOTE: remember to add the TAB character before the command part

#Typing 'make' will invoke the first target entry in the file
storm: storm.cpp
	g++ -o storm storm.cpp



